### PR TITLE
Fix additional_attrs to add attributes via driver, not RM.

### PR DESCRIPTION
**Pull request by JTCunning**
This will fix `create()` throwing an exception about the instance not being assigned to the driver we're trying to assign it to.

### CODE REVIEW

**Comment by plathrop** [comment]
Looks good to me, but get another +1 before proceeding.

**Comment by thekad** [comment]
Is the ec2connectionmanager in the same terrible place?

**Comment by motivator** [comment]
+1 pending investigation of kad's question.

**Comment by thekad** [comment]
@JTCunning also would be nice to note what are the implications of "fixing" existing instances, like, are those still properly handled by the RM?

**Comment by JTCunning** [comment]
@thekad / @motivator: Tested the reconciliation method and made sure allocating from ec2 RM worked.

**Pull request merged**
